server.port=8888
spring.application.name=hermandad-config-server
spring.profiles.active=${CONFIG_SERVER_PROFILE:native}
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_URI:file:../hermandad-project-config}
