spring.application.name=hermandad-project-config-server
server.port=8888
spring.cloud.config.server.native.search-locations=${CONFIG_REPOSITORY_LOCATION:file:/config-repository}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always