services.gestion-usuarios.url=${GESTION_USUARIOS_URL:http://localhost:8081}
services.gestion-hermandades.url=${GESTION_HERMANDADES_URL}
services.gestion-inventario.url=${GESTION_INVENTARIO_URL}
services.gestion-personajes.url=${GESTION_PERSONAJES_URL:http://localhost:8084}
services.gestion-recompensas.url=${GESTION_RECOMPENSAS_URL}
services.gestion-recorridos.url=${GESTION_RECORRIDOS_URL}
services.gestion-ciudad.url=${GESTION_CIUDAD_URL}
services.gestion-pasos.url=${GESTION_PASOS_URL}
