logging.level.com.hermandadproject.gestionusuarios=DEBUG


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hermandad-project}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Usuario-1}

spring.mail.username=${MAIL_USERNAME:java8.oca@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zhjp oixu edjd dorh}
hermandad.user.password-reset.token-expiration-minutes=30
hermandad.mail.reset-password-url=http://localhost:5173/restaurar-contrasena
hermandad.mail.activation-url=http://localhost:5173/activar-cuenta?
