spring.datasource.url=${GESTION_EVENTOS_DB_URL}
spring.datasource.username=${GESTION_EVENTOS_DB_USERNAME}
spring.datasource.password=${GESTION_EVENTOS_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.liquibase.enabled=true

hermandad.eventos.default-calendar=general
