logging.level.com.hermandadproject.gestionpersonajes=${GESTION_PERSONAJES_LOG_LEVEL:DEBUG}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hermandad-project}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Usuario-1}