spring.datasource.url=${GESTION_PERSONAJES_DB_URL}
spring.datasource.username=${GESTION_PERSONAJES_DB_USERNAME}
spring.datasource.password=${GESTION_PERSONAJES_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=${GESTION_PERSONAJES_PORT:8084}

logging.level.root=INFO
logging.level.com.hermandadproject.gestionpersonajes=${GESTION_PERSONAJES_LOG_LEVEL:INFO}

hermandad.personajes.initial-energy=100
