export const partidasMock = [
  {
    id: '1',
    nombre: 'Real Hermandad de la Luz',
    ciudad: 'Sevilla',
    tipo: 'Hermandad de Penitencia',
    devocion: 82,
    solemnidad: 90,
    prestigio: 71,
    presupuesto: 45630,
    ultimoAcceso: 'Ayer, 18:42',
    ultimaPartida: true,
  },
  {
    id: '2',
    nombre: 'Hermandad del Santísimo Cristo',
    ciudad: 'Málaga',
    tipo: 'Hermandad de Penitencia',
    devocion: 74,
    solemnidad: 65,
    prestigio: 58,
    presupuesto: 32150,
    ultimoAcceso: '3 días atrás',
    ultimaPartida: false,
  },
  {
    id: '3',
    nombre: 'Hermandad de la Esperanza',
    ciudad: 'Córdoba',
    tipo: 'Hermandad de Gloria',
    devocion: 68,
    solemnidad: 55,
    prestigio: 62,
    presupuesto: 28940,
    ultimoAcceso: '1 semana atrás',
    ultimaPartida: false,
  },
];